### PR TITLE
Finish polyline and popup when click + Declare enum for change basemap feature.

### PR DESCRIPTION
**Pull request by hiimBugCreator**
Done location for 3 District + Customize popup when click in bound line + Declare enum for change basemap feature.

### CODE REVIEW

**Review by hauletrung — APPROVED** [review]

**Review by hauletrung — APPROVED** [review]

**Comment by liemvh1998** [comment]
good

**Review by liemvh1998 — APPROVED** [review]
ok

**Review by liemvh1998 — APPROVED** [review]
ok

**Review by liemvh1998 — APPROVED** [review]
ok

**Review by liemvh1998 — APPROVED** [review]
ok

**Review by liemvh1998 — APPROVED** [review]
ok

**Review by liemvh1998 — APPROVED** [review]
ok

**Pull request merged**
